version: '3.8'
services:

  backend:
    build:
      context: .
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/

  nginx:
    image: nginx:1.21.3-alpine
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend

volumes:
  static_value:
  media_value: